### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by Nostrademous** [lenLRX/Dota2_DPPO_bots#4]
`/Users/andrzej.gorski/Projects/Dota2_DPPO_bots/cppSimulator/src/Creep.cpp:10:30: error: non-local lambda expression cannot have a capture-default`
`static int init_CreepData = [&]()->int {`
`.............................^`
`1 error generated.`

Chances are you don't have an issue because you are using g++, however clang will not compile that line. 

Probably should be fixed so the project supports more compilers. I am checking it out on OSX and wanted to play with it.

**Comment by lenLRX** [comment]
Sorry, I am using MSVC and g++, they are happy with this stmt.
